name = "matoous-wiki"
account_id = "f4d60d05dbec6b65aba308c02f8368f7"
compatibility_date = "2026-03-14"
workers_dev = true

[assets]
directory = "./dist"
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"

[observability]
enabled = true
